### ISSUE TITLE
关于高DPI适配问题

### ISSUE THREAD

**Issue by rjtop** [makipom/BlueArchive-Cursors#10]
当前鼠标指针文件内只存在单一尺寸(32x32)，这回导致在屏幕缩放比例大于100%的设备上鼠标指针显示模糊

**Comment by makipom** [comment]
目前还没有计划。 也许在将来。

**Comment by makipom** [comment]
已在“千禧年科技学院版”中修复。
☛ [Blue Archive Cursor Set (Millennium Edition) v1.0](https://github.com/makipom/BlueArchive-Cursors/releases/tag/millennium-1.0)
