### ISSUE TITLE
高分辨率屏幕下鼠标指针模糊

### ISSUE THREAD

**Issue by kira-96** [makipom/BlueArchive-Cursors#11]
我的电脑屏幕分辨率比较高（2K）,鼠标指针看起来比较模糊，希望后续能够优化。

**Comment by makipom** [comment]
「目前还没有计划。 也许在将来。」

**↳** [关于高DPI适配问题](https://github.com/makipom/BlueArchive-Cursors/issues/10)

**Comment by makipom** [comment]
已在“千禧年科技学院版”中修复。
☛ [Blue Archive Cursor Set (Millennium Edition) v1.0](https://github.com/makipom/BlueArchive-Cursors/releases/tag/millennium-1.0)
