### ISSUE TITLE
鼠标编辑形态的动画总是分心

### ISSUE THREAD

**Issue by KargathEx** [makipom/BlueArchive-Cursors#12]
![image](https://github.com/makipom/BlueArchive-Cursors/assets/40135358/341b24cc-81e9-4015-876e-0b7cb7ca00e3)
当鼠标在编辑器中时候呈现为竖直状态，里面偶尔冒出来的蓝色烟雾总会吸引我的注意力。
请问是否有办法关掉这个动态效果，或者作者有没有打算出一个无动态的版本?
谢谢。

**Comment by makipom** [comment]
这是为了更好的引人注目。
但是，是的，我可以为你制作一个非动画版本。

_※Google翻译_

**Comment by makipom** [comment]
将其中 4 个添加到“Experimental”文件夹中。 从存储库下载。

_※Google翻译_
