### ISSUE TITLE
Bad visibility over white background

### ISSUE THREAD

**Issue by Apis035** [makipom/BlueArchive-Cursors#13]
The cursor is a bit hard to see on window with white background, for example as seen on the cursor scheme settings.
![image](https://github.com/makipom/BlueArchive-Cursors/assets/53115851/99c56f59-4baa-49f8-8e64-93fd59eb6ea3)

The shadow is too soft and it is also inconsistent as not all the cursors have the shadow or have lighter shadow than the normal cursor.

My suggestion is make the drop shadow more visible or use an outline. 👍

**Comment by Apis035** [comment]
Another solution is completely remove the shadows and use windows' "Enable pointer shadow". Currently enabling it makes the shadow look weird because cursor's shadow and windows' shadow is mixed.

**Comment by makipom** [comment]
This is a set closely based on the cursor used on the official Chinese website, as such it is **working as intended**.
Although I have plans of experimenting with outline variants (as well as updating them to Win11 60px format) in the future, it isn't a bug and as such I can't say that it would be a fix - rather, it would be something different. And these (~0.4.1) cursors will stay as they are now.

**Comment by makipom** [comment]
Fixed in the "Millennium Edition".
☛ [Blue Archive Cursor Set (Millennium Edition) v1.0](https://github.com/makipom/BlueArchive-Cursors/releases/tag/millennium-1.0)

**Comment by Apis035** [comment]
Thank you! Looks much better.
