### ISSUE TITLE
The top of the pointer is not correct

### ISSUE THREAD

**Issue by Sh1no4** [makipom/BlueArchive-Cursors#2]
![test2222332222120](https://github.com/makipom/BlueArchive-Cursors/assets/137148022/f430a082-aa16-4d18-b222-02c0ee8c05d7)

It doesn't point to the correct trigger position correctly, which makes me very distressed, although the problem is not big, I still raise an issue

**Comment by makipom** [comment]
Ah, it's true, it seems I missed those ones when setting up other cursors' "active area". 
Fixes are rolled out, please re-download the archive from the Releases page.
