### ISSUE TITLE
Change the 'Title' field in Install.inf to English.

### ISSUE THREAD

**Issue by xiaole3349** [makipom/BlueArchive-Cursors#3]
If the 'Title' field is not changed to English, it might appear as garbled characters in Windows systems using other languages.
like this:
<img width="1280" alt="屏幕截图 2023-08-07 051331" src="https://github.com/makipom/BlueArchive-Cursors/assets/40677760/71efaf06-24d2-42b8-9318-0d086bb79a18">

**Comment by makipom** [comment]
Done 👌
