### ISSUE TITLE
Can you make a smaller version of the mouse cursors?

### ISSUE THREAD

**Issue by skMayi** [makipom/BlueArchive-Cursors#4]
Hello makipom,
I really like the cursors you made, But I used it for a while and found that cursor is a little too big,I hope you can make a smaller version, thank you!

**Comment by makipom** [comment]
Done 👌
I've resized them to 0.7 of their original size and set their "active zones" accordingly. Although, of course, nothing much more. So this is an experimental version, if there would be problems with it - feel free to contact me through the Issues here or other means; I'll try to fix them.

https://github.com/makipom/BlueArchive-Cursors/releases/tag/mini-ver0.3.2
