### ISSUE TITLE
May the icons support Gnome?

### ISSUE THREAD

**Issue by ADP-P-P** [makipom/BlueArchive-Cursors#7]
I tried to convert the .cur files to the xcursor format with [win2xcur](https://github.com/quantum5/win2xcur), but gnome and the tweaker couldn't support replace cursors by raw xcursors, even pack them up yet. I wonder, may this repository suppoer gnome?

**Comment by makipom** [comment]
To be frank - **I don't really know**. 
These cursors were created in Windows, for Windows. If there is anything happening when converting them to a different format for another OS to use in - I can't really say anything on this part, nor could I check. 

You're free to try and convert them on your own in any way or shape you want, but I won't be able to vouch for the converted ones' ability to work properly in said environment. 
Nor do I have any plans of officially supporting any platform other than Windows.
