### ISSUE TITLE
关于处于链接选择状态时鼠标指针的样式

### ISSUE THREAD

**Issue by Mascot-N** [makipom/BlueArchive-Cursors#8]
我注意到您在目前的版本中，正常选择时的样式为白色而在链接选择时为蓝色。
实际上在中文官网上，当鼠标指针悬停于某些选项上时，光标的尖端会出现一个圈，而颜色的变化则取决于你是否处于首页。
希望能够改进！

**Comment by makipom** [comment]
确实如此，但这样的条件游标在 Windows 中也是不可能的（至少据我所知）。 关于圆圈 - 这本身并不是不可能的，但由于尺寸问题，到目前为止我无法生产一个除了“迷你”版本的光标之外的圆圈，所以到目前为止 - 它还处于“ 开发的实验性方面。

※Google翻译

**Comment by makipom** [comment]
如果您现在从该存储库的 Experimental 文件夹下载它，您可以尝试迷你版本的实验版本。

※Google翻译

**Comment by makipom** [comment]
已在“千禧年科技学院版”中修复。
☛ [Blue Archive Cursor Set (Millennium Edition) v1.0](https://github.com/makipom/BlueArchive-Cursors/releases/tag/millennium-1.0)
