### ISSUE TITLE
关于文本选择时的动态光标颜色填充不完全

### ISSUE THREAD

**Issue by duwei3040** [makipom/BlueArchive-Cursors#9]
大佬ヾ(•ω•`)o
我发现文本选择时的动态光标在选择时蓝色并完全从底部升起而是从一半的位置上升
可否让颜色从底部升起并加深把蓝色加深

**Comment by makipom** [comment]
这是一个有意的设计选择。
但是，我做了一个像你描述的那样的。 现在，您可以通过从此存储库中的 Experimental 文件夹下载它来尝试它。
就是“text_better_nnn”和“text_better_nnn-mini”。

※Google翻译
